import type { Analysis } from '../analyze/types.js';
import type { Workspace } from '../workspace.js';
import type { Theme } from './plan.js';

const SERIF = /serif|georgia|times|garamond|playfair|merriweather|lora|baskerville|caslon|didot|bodoni|tiempos|canela|freight/i;
const MONO = /mono|code|courier|consolas/i;

function fontStack(name: string) {
  const clean = name.replace(/["']/g, '').trim();
  const generic = MONO.test(clean) ? 'ui-monospace, monospace' : SERIF.test(clean) && !/sans/i.test(clean) ? 'Georgia, "Times New Roman", serif' : 'ui-sans-serif, system-ui, -apple-system, "Segoe UI", Helvetica, Arial, sans-serif';
  if (!clean || /^(system-ui|-apple-system|sans-serif|serif)$/i.test(clean)) return generic;
  return `"${clean}", "Inter", ${generic}`;
}

export function themeCss(t: Theme): string {
  return `/* Design tokens – generated by the agent from the analyzed site.
   Tailwind v4 turns every --color-* into utilities (bg-primary, text-muted-foreground, ...).
   Edit here to restyle the whole site. */
@theme {
  --color-primary: ${t.primary};
  --color-primary-foreground: ${t.primaryForeground};
  --color-secondary: ${t.secondary};
  --color-secondary-foreground: ${t.secondaryForeground};
  --color-background: ${t.background};
  --color-foreground: ${t.foreground};
  --color-muted: ${t.muted};
  --color-muted-foreground: ${t.mutedForeground};
  --color-accent: ${t.accent};
  --color-border: ${t.border};
  --font-heading: ${fontStack(t.headingFont)};
  --font-body: ${fontStack(t.bodyFont)};
  --radius-brand: ${Math.max(0, Math.round(t.radius))}px;
  --container-site: ${Math.round(t.containerWidth || 1200)}px;
}
`;
}

export function appTsx(sectionNames: string[]): string {
  const imports = sectionNames.map((n) => `import ${n} from './components/sections/${n}';`).join('\n');
  const body = sectionNames.map((n) => `      <SectionBoundary name="${n}">\n        <${n} />\n      </SectionBoundary>`).join('\n');
  return `import { SectionBoundary } from './components/ui/SectionBoundary';
${imports}

/** Page composition – each section is isolated in an error boundary. */
export default function App() {
  return (
    <div className="min-h-screen bg-background text-foreground font-body">
${body}
    </div>
  );
}
`;
}

/** Section order as currently declared in App.tsx (source of truth after user edits). */
export function sectionsFromApp(app: string): string[] {
  return [...app.matchAll(/<SectionBoundary\s+name="([^"]+)"/g)].map((m) => m[1]);
}

export async function writeScaffold(ws: Workspace, a: Analysis, siteName: string, theme: Theme) {
  await ws.write('src/theme.css', themeCss(theme));
  let html = await ws.read('index.html');
  const esc = (s: string) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;');
  html = html.replace(/<title>.*<\/title>/, `<title>${esc(a.title || siteName)}</title>`);
  html = html.replace('<html lang="en">', `<html lang="${a.lang.slice(0, 5) || 'en'}">`);
  const head = [...a.fontHead];
  if (a.description) head.push(`<meta name="description" content="${esc(a.description).replace(/"/g, '&quot;')}" />`);
  if (a.favicon) head.push(`<link rel="icon" href="${a.favicon}" />`);
  html = html.replace('<!--FONTS-->', head.join('\n    ') || '');
  await ws.write('index.html', html);
}
